package actions

import (
	"fmt"
	"sort"
	"strings"
	"encoding/json"
	"github.com/PaesslerAG/jsonpath"
	"regexp"
	exargs "src/exeiac/arguments"
	exinfra "src/exeiac/infra"
	exstatuscode "src/exeiac/statuscode"
)

var (
	specialTriggers    = map[string]*regexp.Regexp{}
	specialTriggersEnd = regexp.MustCompile(`) *$`)
)

// The init function is a special function in Go that is executed automatically when the package is initialized
func init() {
	specialTriggersStr := []string{
		`equal`,
		`contains`,
		`match`,
	}
	var r *regexp.Regexp
	for _, s := range specialTriggersStr {
		r = regexp.MustCompile(`^ *` + s + `(`)
		specialTriggers[s] = r
		r = regexp.MustCompile(`^ *not_` + s + `(`)
		specialTriggers[`not_` + s] = r
	}
}

type jsonPath string
type brickName string
type pjson *[]byte
type isSimpleType bool // True if NotExist, String, Number, Boolean or Null. False if Object or Array
type Events map[brickName][exinfra.Source][jsonPath]isSimpleType //don't contain the event value (too heavy) that belongs to execution type.
	// The value of type isSimpleType is only used to know if it's a direct diff of flattened Json  or an "herited diff".
	// I don't know if the value will be really useful but it should, at least, be not so heavy
	// Actually the aim it to let search easily if an event or an output's change has occured not to acces the value

type execution struct {
	Triggered		bool // if the execution was necessary due to a trigger or explicitly asked by argument
	Passed			bool // if the execution was runned or skipped (perhaps useless due to executions.index)
	Skipped			bool // if the execution was skipped
	Brick	    	*exinfra.Brick // the brick to execute
	Action      	string		   // the action to execute on the brick
	// Args	    	[]string       // the arguments (perhaps useless) useless because difficult to be built progressively use Brick.Dependencies[n].Value of type []byte
	StatusCode 	    int            // the status_code of the execution
	Events	    	[]byte		   // the events generated by the execution
	ChangedOutputs	ChangedOutputs // the output changed by the execution
	Err		    	error		   // the error generated by the execution
}

type Run struct {
	List 	      []execution             // the execution list that will growth during this execiac runs
	Args          []string                // the arguments of all the executions
	Configuration *exargs.Configuration	 // the configuration of exeiac (perhaps useless)
	Index         int		             // the index in list of the current execution
	Events        Events		             // to let search easily if an event or an output's change have occured (doesn't contain the value)
	Infra	      *exinfra.Infra
}

func NewRun(i *exinfra.Infra, c *exargs.Configuration, bricksToExecute *exinfra.Bricks) (r *Run) {
	
	r.Args = c.Arguments // to check
	r.Infra = i
	r.Configuration = c
	r.Index = 0
	
	insertPlace := 0
	
	for b := bricksToExecute {
		execution := make(execution)
		insertPlace = r.InsertExecution(insertPlace, execution{
			Triggered: true,
			Passed: false,
			Skipped: false,
			Brick: b,
			Action: c.Action,
			StatusCode: 0,
			Events: nil,
			ChangedOutputs: nil,
			Err: nil
		})

		// search all possible triggered events
		// search all possible triggered execution

		for dp := r.Infra.GetLinkedPrevious(b) {
			triggeredActions := []string{}
			for _, deps := range dp.Dependencies {
				if deps.From.Brick.Index == b.Index {
					triggeredActions = append(triggeredActions, deps.TriggeredAction)
				}
			}
			action.sort(triggeredActions) // TODO
			triggeredActions = action.RemoveDuplicates(triggeredActions) // TODO

			for action := triggeredActions {
				_ = r.InsertExecution(insertPlace, execution{
					Triggered: false,
					Passed: false,
					Skipped: false,
					Brick: b,
					Action: action,
					StatusCode: 0,
					Events: nil,
					ChangedOutputs: nil,
					Err: nil
				}
			}
		}		
	}
}

func (r Run) InsertExecution(index int, e execution) int {
	for i := index; i < len(r.list); i++ {
		if e.Brick.Index == r.list[i].Brick.Index {
			if e.Action == r.list[i].Action {

				return i
			}
			// TODO: check action order, check action shrinking... (have to be more rigorous)
			r.list = slices.Insert(r.list, i, e)

			return i
		} else if e.Brick.Index > r.list[i].Brick.Index {
			r.list = slices.Insert(r.list, i, e)

			return i
		}
	}
	r.list = append(r.list, e)
	return len(r.list)
}

func (e executions) IsFinished() bool {
	if e.index + 1 == len(e.list) {
		return true
	}
	return false
}

func (e execution) IsNeeded(executions *executions) bool {
	if e.Triggered {

		return true
	}

	for dName, d := range e.Brick.Dependencies {
		if d.IsDependencyNeeded(e.Action) {
			if _, exists := executions.Events[d.From.Brick.Name][d.From.Source][d.From.JsonPath]; exists {
				
				return true
			}
		}
	}

	return false
}

func (r Run) run(i int) (err error) {
	e := *r.list[i]
	b := e.Brick
	a := e.Action
	r.index++
	// const TAG_OK = "OK"
	// const TAG_NO_CHANGE = "NO_CHANGE"
	// const TAG_DONE = "DONE"
	// const TAG_ERROR = "ERR"
	// const TAG_SKIP = "SKIP"
	// const TAG_DRIFT = "DRIFT"
	// const TAG_MAY_DRIFT = "DRIFT?"

	if e.Triggered && !e.Skipped {
		stdout := exinfra.StoreStdout{} // if you want to read and not display output

		// ENRICH OUTPUTS BEFORE EXEC
		preExecOutputErr := enrichOutputsBeforeExec(b, r.Infra, a)
		if preExecOutputErr != nil {
			e.StatusCode = exstatuscode.ENRICH_ERROR
			err = fmt.Errorf("actions.executions.run(%d):\n" +
				"actions.enrichOutputsBeforeExec(%s, %s):\n%v",
				i, b.Name, a, preExecOutputErr)
		}
		
		// GET ACTION ENVS
		if err != nil {
			envs, preExecGetEnvsErr := writeEnvFilesAndGetEnvs(b, a)
		}
		if preExecGetEnvsErr != nil {
			e.StatusCode = exstatuscode.ENRICH_ERROR
			err = fmt.Errorf("actions.executions.run(%d):\n" +
				"actions.writeEnvFilesAndGetEnvs(%s, %s):\n%v",
				i, b.Name, a, preExecGetEnvsErr)
		}

		// GET WRITERS // to code when it will be specified in describe_module_for_exeiac outputs
		writers = [ os.Stdout, os.Stderr ]
		preExecGetWritersErr = nil
		// if err != nil {
		// 	writers, preExecGetWritersErr = b.Module.getWriters(a) 
		// }
		// if preExecGetWritersErr != nil {
		// 	e.StatusCode = exstatuscode.ENRICH_ERROR
		// 	err = fmt.Errorf("actions.executions.run(%d):\n" +
		// 		"actions.??????????????????????(%s, %s):\n%v",
		// 		i, b.Name, a, preExecGetWritersErr)
		// }

		// MODULE EXEC
		if err != nil {
			actionEvents, actionErr := b.Module.Exec(b, a, conf.OtherOptions, envs, writers)	
		}
		if actionErr != nil {
			e.StatusCode = exstatuscode.MODULE_ERROR // have to track if it's MODULE or a RUN_ERROR before or after the module run
			err = fmt.Errorf("actions.executions.run(%d): brick.module.Exec()-> %s.%s.Exec()" +
				"infra.Module.Exec(%s, %s):\n%v",
				i, b.Name, b.Module.Name,
				b.Name, a, actionErr)
		}
		
		// POST EXEC OUTPUT
		if err != nil {
			_, postOutputErr := b.Module.Exec(b, "output", []string{}, envs, &stdout)
		}
		if postOutputErr != nil {
			e.StatusCode = exstatuscode.RUN_ERROR
			err = fmt.Errorf("actions.executions.run(%d): brick.module.Exec()-> %s.%s.Exec()" +
				"infra.Module.Exec(%s, output):\n%v",
				i, b.Name, b.Module.Name,
				b.Name, postOutputErr)
		}

		// REGISTER CREATED EVENTS
		if err != nil {
			compareOutputErr = r.AddEvents(i, actionEvents, b.Output, stdout.Output, infra)
		} 
		if compareOutputErr != nil {
			e.StatusCode = exstatuscode.RUN_ERROR
			err = fmt.Errorf("actions.executions.run(%d):" +
				"executions.AddEvents(%v, %v):\n%v",
				i, b.Output, stdout.Output, compareOutputErr)
		}
		
		
		// manage all possible error
		if err != nil {
			r.skipFollowing(i)
			r.Stings()
		}

		// discover and mark triggered brick
		r.triggerExecutions(i, actionEvents, b.Output, stdout.Output)  // ???? les events sont pas déjà créé ? 

		// set new brick output
		b.Ouput = stdout.Output

	}
	return
}


func getJsonPathValue(inputJSON []byte, jsonPath string) ([]byte, error) {
	var jsonData interface{}

	err := json.Unmarshal(inputJson, &jsonData)
	if err != nil {
		return nil, fmt.Errorf("error unmarshaling JSON: %v", err)
	}

	value, err := jsonpath.Get(jsonPath, jsonData)
	if err != nil {
		value = nil
	}

	resultJson, err := json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling result JSON: %v", err)
	}

	return resultJson, nil
}

func testEq(a, b []byte) bool {
    if len(a) != len(b) {
        return false
    }
    for i := range a {
        if a[i] != b[i] {
            return false
        }
    }
    return true
}

func specialTriggerTypeTest(test string, value []byte) (o bool, err error) {
	var s string
	var function string
	var function_result bool
	o = false

	for k, r := specialTriggers {
		if r.MatchString(test) {
			s = r.ReplaceAllString(test, '')
			s = specialTriggersEnd.ReplaceAllString(test, '')
			function = k
			break
		}
	}
	switch k {
	case "equal", "not_equal":
		if string(value) == s {
			o = true
		}
	case "contains", "not_contains":
		err = fmt.Errorf("specialTriggerTypeTest(unvalid test: \"%s\")", k)
		
		return
	case "match", "not_match":
		reg, err = regexp.Compile(s)
		if err != nil {
			err = fmt.Errorf("specialTriggerTypeTest.match(regex unvalid: \"%s\") %v", string(value), err)
			
			return
		}
		if reg.Match(value) {
			o = true
		}
	default:
		// case contains differ for list or dict. TO DO later.
		err = fmt.Errorf("specialTriggerTypeTest(unvalid test: \"%s\")", k)

		return
	}

	if strings.HasPrefix(function, "not_") {
		o = !o
	}

	return
	
}

func (e *executions) addExecution(a exinfra.EventAttrib) {

	Triggered		bool // if the execution was necessary due to a trigger or explicitly asked by argument
	Passed			bool // if the execution was runned or skipped (perhaps useless due to executions.index)
	Skipped			bool // if the execution was skipped
	Brick	    	*exinfra.Brick // the brick to execute
	Action      	string		   // the action to execute on the brick
	StatusCode 	    int            // the status_code of the execution
	Events	    	[]byte		   // the events generated by the execution
	ChangedOutputs	ChangedOutputs // the output changed by the execution
	Err		    	error		   // the error generated by the execution
	
	found = false
	index := e.index+1
	for  index < len(e.list) {
		if a.DepsTuples.Brick.Name == e.list[index].Brick.Name {
			found = true
			break
		}
		index++
	}

	e.list[index].Triggered = true
	e.list[index].Action =  
	a.DepsTuples.Brick.Dependencies[a.DepsTuples.Name].Value = a.Value

}

func (e *executiions) addExecutionIfNeeded(a exinfra.EventAttrib) error {
	for _, v := range a.DepsTuples {
		d = v.Brick.Dependencies[v.Name]
		d.Value = a.Value
		switch  d.TriggerType {
		case "weak":
			continue
		case "classic":
			// add execution
		case "is_true()", "is_true":
			if testEq([]byte("true"), a.Value) {
				// add execution
			} 
		case "is_false()", "is_false":
			if testEq([]byte("false"), a.Value) {
				// add execution
			}
		case "is_null()", "is_null":
			if testEq([]byte("null"), a.Value) ||
				testEq([]byte{}, a.Value) {
				// add execution
			}
		case "is_not_null()", "is_not_null":
			if ! testEq([]byte("null"), a.Value) &&
				! testEq([]byte{}, a.Value) {
				// add execution
			}
		case "is_empty()", "is_empty":
			if testEq([]byte("[]"), a.Value) ||
				testEq([]byte("{}"), a.Value) ||
				testEq([]byte("\"\""), a.Value) ||
				testEq([]byte{}, a.Value) {
				// add execution
			}
		case "is_not_empty()", "is_not_empty":
			if ! testEq([]byte("[]"), a.Value) &&
				! testEq([]byte("{}"), a.Value) &&
				! testEq([]byte("\"\""), a.Value) &&
				! testEq([]byte{}, a.Value) {
				// add execution
			}
		case "is_nothing()", "is_nothing":
			if testEq([]byte("null"), a.Value) || 
				testEq([]byte("[]"), a.Value) || 
				testEq([]byte("{}"), a.Value) ||
				testEq([]byte("\"\""), a.Value) ||
				testEq([]byte{}, a.Value) {
				// add execution
			}
		case "is_not_nothing()", "is_not_nothing":
			if ! testEq([]byte("null"), a.Value) && 
				! testEq([]byte("[]"), a.Value) &&
				! testEq([]byte("{}"), a.Value) &&
				! testEq([]byte("\"\""), a.Value) &&
				! testEq([]byte{}, a.Value) {
				// add execution
			}
		default:
			specialTriggerTypeTest()
		}

		if d.TriggerType == "weak" {
			continue
		}
	}
}

func (r *Run) addExecutions(
	i int, 
	actionEvents []byte, // actionEvents is not an []byte but a map[string]interface{} but maybe it is : module line 219 : events[eventName], err = os.ReadFile(path) 
	preOutput []byte, 
	postOutput []byte, 
) (
	err error
) {
	brickName := r.list[i].Brick.Name
	src := exinfra.OUTPUT_SOURCE
	//map[brickName][src][jsonPath][]EventAttrib 
	for jsonPath, event := range r.infra.Events[brickName][src] {
		initialValue = getJsonPathValue(preOutput, jsonPath)
		endValue = getJsonPathValue(postOutput, jsonPath)
		if !testEq(initialValue, endValue) {
			r.infra.Events[brickName][src][jsonPath].HasOccured = true
			
			// ADD EXECUTION
			r.AddExecution()
		}
		r.infra.Events[brickName][src][jsonPath].Value = endValue
	}

	src = exinfra.EVENT_SOURCE
	jsonNull = []byte("null")
	for jsonPath, event := range r.infra.Events[brickName][src] {
		value = getJsonPathValue(actionEvents, jsonPath)
		if !testEq(value, jsonNull) {
			r.infra.Events[brickName][src][jsonPath].HasOccured = true
			r.infra.Events[brickName][src][jsonPath].Value = value
		}
	}

}

func (r *Run) skipFollowing(index int) {
	for i=(index+1) ; i<len(r.list) ; i++ {
		r.list[i].Skipped = true
		r.list[i].Triggered
	}
}


// func addComplexTypeJsonPath(path jsonPath) (jsonPaths []jsonPath) {
// 	jsonpathSlice := strings.Split(path, ".")
// 	var jsonPath jsonPath
// 	for n:=0; n<len(jsonpathSlice); n++ {
// 		jsonPath = ""
// 		for i:=0 ; i<=n ; i++ {
// 			jsonPath = jsonPath + jsonpathSlice[i]
// 		}
// 		jsonPaths = append(jsonPaths, jsonPath)
// 	}
// 	return
// }

// func (e *executions) addEvent(j jsonPath, brickName string, src exinfra.Source) {
// 	var jsonPath jsonPath
	
// 	jsonpathSlice := strings.Split(j, ".")
// 	e.Events[brickName][src][j] = true
	
// 	for n:=1; n<len(jsonpathSlice); n++ {
// 		jsonPath = ""
// 		for i:=0 ; i<n ; i++ {
// 			jsonPath = jsonPath + jsonpathSlice[i]
// 		}
// 		e.Events[brickName][src][jsonPath]false
// 	}
// }

// func (e *executions) addEvents(
// 	i int, 
// 	actionEvents []byte, // actionEvents is not an []byte but a map[string]interface{} but maybe it is : module line 219 : events[eventName], err = os.ReadFile(path) 
// 	preOutput []byte, 
// 	postOutput []byte, 
// ) (
// 	err error
// ) {
// 	var brickOutput map[jsonPath]isSimpleType

// 	comparedJson, areEqual, err := CompareJsons(b.Output, stdout.Output)
// 	if err != nil {
// 		err = fmt.Errorf("addEvents(e.list[i].Brick.Name): call to CompareJsons failed %v", err)
		
// 		return
// 	}

// 	for jsonPath, _ := range comparedJson {

// 		e.addEvent(jsonPath, e.list.Brick.Name, exinfra.OUTPUT_SOURCE)
// 	}

// 	// add actionsEvents
// 	flattenEvents := FlattenJson(actionEvents, "")
// 	for jsonPath, _ := range flattenEvents {
// 		e.addEvent(jsonPath, e.list[i].Brick.Name, exinfra.EVENT_SOURCE)
// 	}

// }

// func (e *executions) getParentJsonPaths(j jsonPath) (list []JsonPath)  {
// 	var jsonPath jsonPath
// 	jsonpathSlice := strings.Split(j, ".")
	
// 	for n:=1; n<len(jsonpathSlice); n++ {
// 		jsonPath = ""
// 		for i:=0 ; i<n ; i++ {
// 			jsonPath = jsonPath + jsonpathSlice[i]
// 		}
// 		list = append(list, jsonPath)
// 	}

// 	return
// }

